# Generated by Django 5.2.9 on 2026-04-14 20:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('grid', models.JSONField()),
                ('dictionary_language', models.CharField(default='English', max_length=25)),
                ('solution_words', models.JSONField(blank=True, default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words_found_count', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boggle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['total_time_seconds', '-words_found_count', '-saved_at'],
            },
        ),
    ]
