# Generated by Django 5.2.9 on 2026-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='user',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='player_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='dictionary_language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish')], default='english', max_length=20),
        ),
    ]
